name: segment-sam
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.2.6
  - pip:
      - napari==0.6.1
      - copick==1.20.0
      - cryoet-data-portal==4.8.0
      - ome-zarr==0.11.1
      - s3fs==2026.2.0
      - zarr==2.18.3
      - nnInteractive==1.1.3
      - napari-nninteractive==1.0.6
